version: "2"
services:
  app:
    build: .
    links:
      - neo4jdb
      - mongodb
    image:
      eugeniaoshurko/kamistudio
    ports:
      - "5000:5000"
  neo4jdb:
    image: neo4j:3.5
    environment:
      - NEO4J_AUTH=neo4j/admin
      - "NEO4J_dbms_security_procedures_unrestricted: algo.*, apoc.*"
    volumes:
      - $PWD/neo4j_configs/data:/data
      - $PWD/neo4j_configs/plugins:/plugins
      - $PWD/neo4j_configs/conf:/conf

    ports:
      - "17474:7474"
      - "7687:7687"
  mongodb:
    image: mongo:3.4.21
