version: "2"
services:
  app:
    build: .
    links:
      - neo4jdb
      - mongodb
    image:
      eugeniaoshurko/kamistudio
    ports:
      - "5000:5000"
  neo4jdb:
    image: neo4j:3.5
    environment:
      - NEO4J_AUTH=neo4j/admin
    volumes:
      - ./db/neo4j/data:/data
      - ./db/neo4j/plugins:/plugins
      - ./db/neo4j/conf:/conf
    ports:
      - "17474:7474"
      - "7687:7687"
  mongodb:
    image: mongo:3.4.21
    volumes:
      - ./db/mongo/data:/data/db